<?php

return [
	'title' => 'Заголовок украинский',
	'products-menu' => 'Products',
	'service-menu' => 'Services',
	'service-cifra' => 'Digital Print',
	'service-copy' => 'Copy',
	'service-offset' => 'Offset Printing',
	'service-ufprint' => 'UV printing',
	'service-postprint' => 'Post-printing services',
	'products-vizitki' => 'Business cards',
	'products-bukleti' => 'Booklets',
	'products-catalog' => 'Catalog',
	'products-flaera' => 'Flyer',
	'products-bloknot' => 'Notepad',
	'products-nakleyki' => 'Stickers',
	'materials-menu' => 'Materials',
	'rules-menu' => 'Layout requirements',
	'delivery-menu' => 'Delivery and payment',
	'contacts-menu' => 'Contacts',
	'navigation-menu' => 'Navigation',
	'footer-text-first' => 'PrintHub is a team of enthusiasts created for the fastest and cheapest printing for you',
	'footer-text-second' => 'Our task is to print on your layout at any time, with the highest quality and at a comfortable price.',
	'show-me' => 'Read more',
	'price' => 'Price-List',
	'time-open' => 'Mo-Fr from 9 to 18.',
	'work_examples' => 'Work examples',
];