<?php

return [
	'title' => 'Заголовок русский',
	'products-menu' => 'Продукция',
	'service-menu' => 'Услуги',
	'service-cifra' => 'Цифровая печать',
	'service-copy' => 'Копирование',
	'service-offset' => 'Офсетная печать',
	'service-ufprint' => 'Ультрафиолетовая  печать',
	'service-postprint' => 'Постпечатные услуги',
	'products-vizitki' => 'Визитки',
	'products-bukleti' => 'Буклеты',
	'products-catalog' => 'Каталог',
	'products-flaera' => 'Флаера/Листовки',
	'products-bloknot' => 'Блокнот',
	'products-nakleyki' => 'Наклейки',
	'materials-menu' => 'Материалы',
	'rules-menu' => 'Требования к макетам',
	'delivery-menu' => 'Доставка и оплата',
	'contacts-menu' => 'Контакты',
	'navigation-menu' => 'Навигация',
	'footer-text-first' => 'PrintHub - это команда энтузиастов, созданная для максимально быстрой и дешевой печати для Вас',
	'footer-text-second' => 'Наша задача - в любое время выполнить печать по вашему макету, с соблюдением максимального качества и по комфортной цене.',
	'show-me' => 'Показать',
	'price' => 'Прайс',
	'time-open' => 'Пн-Пт с 9 до 18.',
	'work_examples' => 'Примеры работ',
];