<?php

return [
	'title' => 'Заголовок украинский',
	'products-menu' => 'Продукцiя',
	'service-menu' => 'Послуги',
	'service-cifra' => 'Цифровий друк',
	'service-copy' => 'Копіювання',
	'service-offset' => 'Офсетний друк',
	'service-ufprint' => 'Ультрафіолетовий друк',
	'service-postprint' => 'Післядрукарські послуги',
	'products-vizitki' => 'Візитки',
	'products-bukleti' => 'Буклети',
	'products-catalog' => 'Каталог',
	'products-flaera' => 'Флаєра / Листівки',
	'products-bloknot' => 'Блокнот',
	'products-nakleyki' => 'Наклейки',
	'materials-menu' => 'Матеріали',
	'rules-menu' => 'Вимоги до макетів',
	'delivery-menu' => 'Доставка і оплата',
	'contacts-menu' => 'Контакти',
	'navigation-menu' => 'Навігація',
	'footer-text-first' => 'PrintHub - це команда ентузіастів, створена для максимально швидкої і дешевої друку для Вас',
	'footer-text-second' => 'Наше завдання - в будь-який час виконати друк на вашу макету, з дотриманням максимальної якості та за комфортної ціною.',
	'show-me' => 'Показати',
	'price' => 'Прайс',
	'time-open' => 'Пн-Пт з 9 до 18.',
	'work_examples' => 'Приклади робіт',
];